<a href="https://colab.research.google.com/github/hyedall/data_python/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# python pandas 정리
&nbsp;
&nbsp;


### 데이터프레임 생성
---

In [9]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(10, 26).reshape(4, 4,), 
                  columns = ['a', 'b', 'c' ,'d'])
df

    a   b   c   d
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25




### 데이터프레임 인덱싱
___
1. 열 기준 인덱싱
- 하나의 열 : 시리즈 형태로 가져옴
```python
df[열이름] 
```
&nbsp;
- 두개 이상 : 데이터 프레임으로 가져옴  
(컬럼명을 리스트 형태로 넣기)
```python
df[[열이름1, 열이름2]] 
```
&nbsp;
- 열에 값 대입
```python
df['열이름'] = 값 # 열 전체가 한 값으로 대입됨 
df['열이름'] = 값1, 값2, 값3
df['열이름'] = np.arange(5000, 8900, 1000) # 5000부터 8900까지 1000씩 증가 
```
&nbsp;
2. 행 기준 인덱싱
- 슬라이싱 가능 
```python
df[1:3]
df['행1':'행3'] 
```
- 개별 요소 추출  
행 이름으로 가져오게 되서 주의 필요 !! (위치로 x) 
```python
df['열이름']['행이름'] 
```
&nbsp;
3. 인덱서
- loc 인덱서   df.loc['행이름', '열이름']
  - 행 이름으로 데이터 추출, 행이름으로 슬라이싱도 가능
  - 행 이름으로 여러행 추출 (데이터프레임으로) 
  ```python
df.loc[['행이름1', '행이름2']]
```
  - 인덱스 값으로 조건식 사용 가능

    ```python
    df.loc[df.열이름 > 조건] # 인덱스 값으로 조건식을 줄 수 있음 
    # 인덱스 값을 반환하는 함수의 결과값을 사용
    def sel_row(df):
      return df.열이름 > 조건식
    df.loc[sel_row(df)]
    ```

  - df.loc['행', '열']

In [5]:
# ##### 설정변경코드
# * 변수 명이 두번 이상 출력되어도 모두 콘솔에서 보여줄 것

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [11]:
df.loc[1, 'b':'c'] # 시리즈로 반환
df.loc[[1], 'b':'c'] # 데이터프레임으로 반환

b    15
c    16
Name: 1, dtype: int64

    b   c
1  15  16

In [13]:
df.loc[[0,1], ['b', 'c'] ]

    b   c
0  11  12
1  15  16

- iloc 인덱서 df.iloc[행번호, 열번호]
  - 위치를 나타내는 정수로 인덱스를 받음





&nbsp;
### 데이터프레임 특정 조건 데이터 필터링
___


```python
condition = (df.열이름1 == 조건1) & (df.열이름2 == 조건2) # 조건식 작성

df[condition]
```
```python
df[df.열이름 == 조건]
```

```python
df.loc[df.열이름 > 조건] # 인덱스 값으로 조건식을 줄 수 있음 

# 인덱스 값을 반환하는 함수의 결과값을 사용
def sel_row(df):
  return df.열이름 > 조건식
df.loc[sel_row(df)]

```
&nbsp;


### (추가) 마크다운 문법 
___
- 코드 넣기  

\```python  
  
\``` 
```markdown
&nbsp; # 공백 줄 넣기 
```
- 참고
https://ansohxxn.github.io/blog/markdown/

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

- 코랩 파이참 연결
https://jhy156456.tistory.com/entry/Python-Colab%EC%BD%94%EB%9E%A9%EA%B3%BC-%EB%A1%9C%EC%BB%AC-Pycharm-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0

- 코랩 단축키..